# Geo recode reference year
# To select which geo recode table to use eg. 2021 will use tables grunnkrets2021, kommune2021 etc
year: 2025

# Set encoding
encoding.access: UTF-8
encoding.csv: Latin-1

# Paths 
root: "O:/Prosjekt/FHP/PRODUKSJON"
dumps: "RUNTIMEDUMP"
dumpdir: "RUNTIMEDUMP"
filegroups.ny: "PRODUKTER/MELLOMPROD/R/STABLAORG/NYESTE"
filegroups.dat: "PRODUKTER/MELLOMPROD/R/STABLAORG/DATERT"
kubedir: "PRODUKTER/KUBER"
# Mapper under kubedir for outputfiler
kube.ny: "KOMMUNEHELSA/NYESTE/R"
kube.dat: "KOMMUNEHELSA/DATERT"
kube.specs: "KOMMUNEHELSA/SPECS"
kube.qc: "KOMMUNEHELSA/QC"
fhpF: "FRISKVIK_FYLKE"
fhpK: "FRISKVIK_KOMM"
fhpB: "FRISKVIK_BYDEL"
ovpF: "OVP_FYLKE"
ovpK: "OVP_KOMM"
ovpB: "OVP_BYDEL"

# Scripts and databases
stataprikkfile: "BIN/Z_Statasnutter/StataPrikking_MASTER.do"
db: "STYRING/KHelsa.mdb"
logg: "STYRING/KHlogg.mdb"

# columns
kolorgs: 
 - GEO
 - AAR
 - KJONN
 - ALDER
 - UTDANN
 - INNVKAT
 - LANDBAK
 - TAB1
 - TAB2
 - TAB3
 - VAL1
 - VAL2
 - VAL3
taborgs: 
 - GEO
 - AAR
 - KJONN
 - ALDER
 - TAB1
 - TAB2
 - TAB3
valcols: 
  "MT": "MALTALL"
  "T": "TELLER"
  "N": "NEVNER"
  "RATE": "RATE"
  "SMR": "SMR"
  "MEIS": "MEIS"
  "ST": "sumTELLER"
  "SN": "sumNEVNER"
  "SPT": "sumPREDTELLER"
  "RN": "RATE.n"
khtabs:
  - GEO
  - AAR
  - KJONN
  - ALDER
  - UTDANN
  - INNVKAT
  - LANDBAK
profiltabs: 
 - GEO 
 - AAR
 - KJONN
 - ALDER
 - UTDANN
 - INNVKAT
 - LANDBAK
 - ETAB
profilvals: 
 - sumTELLER
 - sumNEVNER
 - RATE
 - MALTALL
 - sumPREDTELLER
 - PREDTELLER
 - SMR
 - NORM
 - MEIS
 - RATE.n
qcvals: 
 - TELLER
 - NEVNER
 - sumTELLER
 - sumNEVNER
 - RATE.n
 
# values and other parameters
totals:
  Gn: "L"
  K: 0
  U: 0
  # S: 0
  L: 0
  In: 0
geo_illegal: "GGG"
alder_illegal: "888_888"
alder_ukjent: "999_999"
aar_illegal: "8888_8888"
illegal: "8"
defdumpformat: "CSV"
amin: 0
amax: 120
anon_svakandel: 0.5
anon_hullandel: 0.2
anon_tot_tol: 0.2

# testing
test.db: "STYRING/test/KHELSAtest.mdb"
test.logg: "STYRING/test/KHloggtest.mdb"
