# Geo recode reference year
# To select which geo recode table to use eg. 2021 will use tables grunnkrets2021, kommune2021 etc
year: 2025

# Set encoding
encoding.access: UTF-8
encoding.csv: Latin-1

# Paths 
root: "O:/Prosjekt/FHP/PRODUKSJON"
folder.db: "STYRING"
dumps: "RUNTIMEDUMP"
filegroups: "PRODUKTER/MELLOMPROD/R/STABLAORG"
kubedir: "PRODUKTER/KUBER/KOMMUNEHELSA"
fhpF: "PRODUKTER/KUBER/FRISKVIK_FYLKE"
fhpK: "PRODUKTER/KUBER/FRISKVIK_KOMM"
fhpB: "PRODUKTER/KUBER/FRISKVIK_BYDEL"
ovpF: "PRODUKTER/KUBER/OVP_FYLKE"
ovpK: "PRODUKTER/KUBER/OVP_KOMM"
ovpB: "PRODUKTER/KUBER/OVP_BYDEL"
dumpdir: "RUNTIMEDUMP"

# Scripts and databases
stataprikkfile: "BIN/Z_Statasnutter/StataPrikking.do"
db: KHelsa.mdb
logg: KHlogg.mdb

# columns
kolorgs: 
 - GEO
 - AAR
 - KJONN
 - ALDER
 - UTDANN
 - INNVKAT
 - LANDBAK
 - TAB1
 - TAB2
 - TAB3
 - VAL1
 - VAL2
 - VAL3
taborgs: 
 - GEO
 - AAR
 - KJONN
 - ALDER
 - TAB1
 - TAB2
 - TAB3
valcols: 
  "MT": "MALTALL"
  "T": "TELLER"
  "N": "NEVNER"
  "RATE": "RATE"
  "SMR": "SMR"
  "MEIS": "MEIS"
  "ST": "sumTELLER"
  "SN": "sumNEVNER"
  "SPT": "sumPREDTELLER"
  "RN": "RATE.n"
profiltabs: 
 - GEO 
 - AAR
 - KJONN
 - ALDER
 - UTDANN
 - INNVKAT
 - LANDBAK
 - ETAB
profilvals: 
 - sumTELLER
 - sumNEVNER
 - RATE
 - MALTALL
 - sumPREDTELLER
 - PREDTELLER
 - SMR
 - NORM
 - MEIS
 - RATE.n
qcvals: 
 - TELLER
 - NEVNER
 - sumTELLER
 - sumNEVNER
 - RATE.n
 
# values
totals:
  Gn: "L"
  K: 0
  U: 0
  S: 0
  L: 0
  In: 0
geo_illegal "GGG"
alder_illegal: "888_888"
alder_ukjent: "999_999"
aar_illegal: "8888_8888"
illegal: "8"
defdumpformat: "CSV"
amax: 120
