# Alle disse verdiene blir lest inn som options i hver pakke (khfunctions.profileyear, qualcontrol.profileyear osv)
# Andre fellesoptions som ikke skal variere ligger i config-khtools og brukes som "khtools.optname"
# Årgang - styrer hvilke mapper friskvikfiler og kvalitetskontrolloutput havner
profileyear: 2027

# Filstier
root: "O:/Prosjekt/FHP/PRODUKSJON"

# databaser
db_khelsa: "STYRING/KHELSA_backend/KHELSA_BE.accdb"
db_geo: "STYRING/raw-khelse/geo-koder.accdb"

